### ISSUE TITLE
Custom validator and how to refer to another field?

### ISSUE THREAD

**Issue by akiva** [dandean/express-form#16]
I am having a difficult time trying to use the custom() method in conjunction with referring to another field outside of the one that I am calling custom() on. Perhaps you can help clarify?

ie.

`validate("deadline.date").custom(function (value) { if (deadline.applicable) { ... } })`

**Comment by dandean** [comment]
This is a tricky one. There's a bit of trickiness going on to support the `equals` validator, and you could just do what that one does: there's a 2nd argument passed to the function after value. This should work for you:

``` js
validate("deadline.date").custom(function (value, data) {
  if (data.deadline.applicable) {
  }
});
```

**Comment by akiva** [comment]
Thanks for the response, however this did not work. To check what `data` returned, I console logged it within the `custom()` callback. Unfortunately, it was `undefined`. :'(

**Comment by dandean** [comment]
Hi @akiva,

Your absolutely right! Sorry about that. I just pushed an update to Github and NPM (0.6.1). The custom validator now gets a 2nd argument which is the formdata. The example I posted in my original response now works. Also, I added a unit test to ensure its functionality:

https://github.com/dandean/express-form/blob/master/test/validate.test.js#L514-521

Thanks for reporting the issue, and let me know if you come across anything else that could use improvement.

Dan

**Comment by akiva** [comment]
The strange thing is that after your push and my update, I can dump / log the `data` object and see what I would expect to, however I cannot test against it. So, for example, my `.custom(function (value, data) { if (data.message.deadline.applicable) { ... } }` is visually verified to be truthy in the log of `data`, yet no test in that callback will catch it or do anything with it whatsoever. It never generated any validation message. :/

**Comment by mjadobson** [comment]
This works for me:

``` javascript
field("deadline.date").custom(function (value, data) {
    if (!data.message.deadline.applicable) {
        throw new Error("%s must be applicable.");
    }
});
```

**Comment by akiva** [comment]
Odd. Why are you using `field()` and not `validate()`? Perhaps it would be easier to see my example...

```
// Only run validation on the deadline date if the deadline applicable is true (or 1 ... or present at all)
validate("message.deadline.date")
  .notEmpty("The deadline date may not be empty.")
  .custom(function (value, data) {
    // Right now we are only testing when we know the applicable is '1'
    if (data.message.deadline.applicable === '1')
      throw new Error("A date must be specified if a deadline applies.");
  }),
```

**Comment by mjadobson** [comment]
`form.field()` is from the API that I introduced in 0.6: https://github.com/dandean/express-form/pull/14 .

I still can't replicate this, can you post a gist that narrows down your issue as much as possible?

**Comment by akiva** [comment]
This is odd. I reviewed your changes and very much liked them, so I updated my code to use `field` and now I get `field is not defined`. Here is a gist of the section of code of interest: https://gist.github.com/45d3e0645b2746b30c21

**Comment by akiva** [comment]
Heh, ignore that field not defined, I forgot to declare it at the top of app.js. Now I am getting SyntaxError: Unexpected identifier, which is odd as everything checks out. I will investigate and if it is somehow related, I will comment again. It may be a wise idea to update the extremely outdated docs here on github to reflect the previous 4 (or so) updates and their changes to the api.

**Comment by mjadobson** [comment]
Docs are fine for now; none of the API changes broke compatibility. The changes are only very recent.

There's no need to do trim() on every field btw, set autoTrim to true in the options.

That error is most likely due to a stray comma or something in your code. Dig through your stack trace to find it.

Can you post the HTML for the form as well? Then I can quickly test this out tomorrow.

**Comment by akiva** [comment]
I found the syntax error that was causing the problems, however, I still cannot get to that deadline applicable when testting. The HTML is here: https://gist.github.com/92f6eab25d31b596298b

**Comment by akiva** [comment]
Again, the issue now is that everything works except my custom validator that should check against `message.deadline.date` only if `message.deadline.applicable` is present/'1'/true. Thanks again!

**Comment by akiva** [comment]
I even tried using `toBooleanStrict()` on the applicable field, thinking somehow forcing it would help... Nope. It's so odd, I can see it passed in the data when I console.log dump it, but I just cannot use it in my custom validator.

**Comment by mjadobson** [comment]
Tested it out, and it all seems to be working correctly. I condensed your code into a single server; let me know if this works for you:

https://gist.github.com/1106341

**Comment by akiva** [comment]
This did not work for me. If you review the errors when deadline applicable is checked but deadline date is empty, it does not return the error set up in the custom validator (a deadline date is required if applicable). I created a custom node app from your gist and still had the same issue. According to NPM all my modules are up-to-date.

**Comment by akiva** [comment]
I think I may have found a solution, but it doesn't really make a great deal of sense...

It seems that if I implement:

```
field('message.deadline.applicable').custom(function (value, data) {
    ...
})
```

to then check the following `message.deadline.date` field for validity first, as opposed to checking the other way around, all is well (which is unfortunate, because then I cannot re-use the validators from `form`. 

If I go back to trying:

```
field('message.deadline.date').custom(function (value, data) {
    if (data.message.deadline.hasOwnProperty('applicable')) {
        console.log("foo");
    } else {
        console.log("bar");
    }
})
```

Not only will it never return "foo" or "bar", after console.logging `value` above the `if()` statement, I discovered `value` is absolutely nothing. Not even `undefined`.

The only reason I can think of why this is happening is due to some level of internal order chaining where you cannot refer to the previous form element within a sibling that occurs afterward?

Very odd.

**Comment by mjadobson** [comment]
Ok, now I understand what you're trying to do.

Basically when a validator throws an error: If that field isn't `required` and it is empty, then express-form just ignores the error.

This is so empty fields that aren't required don't throw errors when you don't want them to. (eg/ an optional e-mail field).

Your problem here is a bit of a doozy then; you can't set the field to `required` because it's not _always_ required, only when the checkbox is ticked, and you're trying to throw an error only when the value is empty.

**Solutions then..**

You could validate the deadline yourself within the applicable field:

``` javascript
field("message.deadline.applicable")
    .custom(function (value, data) {
        // Throw error if applicable and deadline is empty.
        if (value && !data.message.deadline.deadline) {
            throw new Error("Date must be specified if a deadline applies.");
        }
    })
```

I'm not sure whether this is a bug, though it clearly has the capability of causing confusion. Maybe custom validators should be given an option to control the **_don't throw error if value isn't required and empty**_ behaviour.

**Comment by akiva** [comment]
Yes, this was the solution I ended up with.

I am still a little unsure of the rationale... I wasn't setting a `required()` field anywhere within `form` that wasn't always required and present. The issue for me was the fact that even though within field X's `custom()` method I could see the data of field Y, which perhaps had not undergone any validation or filtering, I could not act on Y's value in any way. This seems backwards to me and illogical from a programmatic point of view. If we have a `custom()` function, it should imply full access to all variables within (as we cannot possible imagine before hand what complexity in testing a developer may need).

In any case, I am truly thankful for all your time and help in resolving this.

**Comment by mjadobson** [comment]
Unsure of which rationale? You set your `required()` correctly btw, it was just a bizarre situation where you were trying to throw an error for an empty string, which express-form doesn't do. (Unless you use the special `require()` method).

The `custom()` function only allows you access to one value really, the extra data-set is just a bonus for the `.equals()` proc to do its thing.

If you want to create validator checks that have fields depending on one another, you're probably better off writing your own middleware, as express-form isn't designed to handle that.
